version: '3'
services: 
  game:
    container_name: game_app
    build: .
    environment: 
      - "GOPATH=/go"
    ports: 
      - "8080:8080"
    volumes:
      - ./src:/go/src/game
  mysql:
    image: mysql:5.7
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306